module.exports = {
   myu_phrases: function() {
      return [
		 "Elesis. O jogo de ação do momento!",
		 "Lorde ficou engraçado agora: KEKEKEKEKEKE",
	         "Alguém quer ser meu Mestre Rúnico pra me salvar na praia? <3",
		 "Alguém disse, sacrossanto?",
	         "Que sensação Etérea jogar de EM qqq Parei com as piadas ruins ;-;",
		 "Brilha, brilha, espadinha. Quero ver você julgar!",
	         "Por que a cor do Bluhen não é azul? qqq",
		 "Eve rainha, resto nadinha",
		 "Eu já disse que sou uma bot de familia. Não vou fazer piadas com a Código Absoluto D:",
	         "Jequiti - A essência da Rainha",
		 "Meus sensores estão com pouca memória Ran, acho que a Ara passou por aqui -w-",
		 "As andorinhas voltaram! E a Vishnum também!",
	         "Sem piadas com a Brama nesse canal D:",
		 "O nome do jogo é Elsword? Juro que nem reparei ;-;",
		 "Keep Calm e ESPADA ANCESTRAL!",
	         "CAV o Tunel! CAV o Tunel! Rápido que a Hiena já vem!",
		 "Rosas são vermelhas, violetas são azuis. DFO é praquele lado, pelo amor de Jesus!",
	         "O ministério da saúde adverte: Jogar de Demolidora pode contrair problemas pulmonares.",
		 "Minerva! Limpeza, maciez e perfume de Rosas.",
		 "Hayaaaa!!!!",
		 "Eu quero levar um Angkor pra casa <3",
		 "Todo natal a Rena some -.-'",
		 "WS tem bom gosto, por isso escolheu o Ventus qq",
	         "Rena sambando na avenida ao som de marchinha de carnaval: ô ô ô Aurora!",
		 "Neste momento uma conferência de Lolis ocorre na sala Luciel",
		 "Quem joga com capricho. Joga com Primor!",
	         "Atitude perversa quem tira sarro da Quiliarca u_u",
		 "Quando que o Raven vem me substituir? -.-'",
		 "Acho que o BM ficou muito Furioso D:",
	         "Redimido, compareça ao RH o quanto antes.",
		 "Pi....Ka....Chunnnng!!!!",
		 "Este último look do Templário Cósmico ficou um ar-ra-so!",
	         "Convidei o Chung para assistir Os caça-fantasmas mas ele não gostou da ideia ;-;",
		 "O DDD pra Add o Add...3ioo38282j83c398c239n. **Fatal Error: Error on NaN Class.** ",
		 "Há quanto tempo não vejo o Esper diabólico!Tá, essa foi péssima :C",
	         "Add cansou de ser engenheiro de dados e resolveu acompanhar o brasileirão!",
		 "Reshian submersa está pegando fogo!",
		 "Vou roubar todos os Poporus da Lupina <3",
		 "Desculpa, tava lavando o cabelo qq",
		 "Me deixa dormirrrrrrrrrrr >w<",
		 "Parabéns! Descobriu a frase super secreta da Myu! Receberá um presente surpresa em 24 horas uwu",
	      	 "Lupina, devolve meu poporu!!!! ;-;",
	         "Esse canal é de Elsword? Me disseram que era da Elesis ;-;",
	         "Myu não pode atender no momento, deixe recado após o sinal: BEEEEEP!",
	         "Clanc! Clanc! Acho que meus neurônios estão enferrujados x_x",
	         "Go! Go! Myurangers!",
	         "Você disse, pipoca?"
		 ];
   }
}
