module.exports = {
   myu_phrases: function() {
      return [
		 "Elesis. O jogo de ação do momento!",
		 "Lorde ficou engraçado agora: KEKEKEKEKEKE",
	         "Alguém quer ser meu Mestre Rúnico pra me salvar na praia? <3",
	         "O que é Immortal!!!!!! Não morre no final!!!!!",
		 "Alguém disse, sacrossanto?",
	         "Que sensação Etérea jogar de EM qqq Parei com as piadas ruins ;-;",
		 "Brilha, brilha, espadinha. Quero ver você julgar!",
	         "Por que a cor do Bluhen não é azul? qqq",
	         "Foice o Apostasia e agora entra o Herrscher.",
		 "Eve rainha, resto nadinha",
		 "Eu já disse que sou uma bot de familia. Não vou fazer piadas com a Código Absoluto D:",
	         "Jequiti - A essência da Rainha",
	         "Sabão Sariel - Para uma limpeza impecável.",
		 "Meus sensores estão com pouca memória Ran, acho que a Ara passou por aqui -w-",
		 "As andorinhas voltaram! E a Vishnum também!",
	         "Sem piadas com a Brama nesse canal D:",
	         "Deixei a Chave da Shiva na Chuva.",
		 "O nome do jogo é Elsword? Juro que nem reparei ;-;",
		 "Keep Calm e ESPADA ANCESTRAL!",
	         "CAV o Tunel! CAV o Tunel! Rápido que a Hiena já vem!",
	         "Se a Elesis fosse de Minas, seria de BH.",
		 "Rosas são vermelhas, violetas são azuis. DFO é praquele lado, pelo amor de Jesus!",
	         "O ministério da saúde adverte: Jogar de Demolidora pode contrair problemas pulmonares.",
		 "Minerva! Limpeza, maciez e perfume de Rosas.",
	         "Optimus Prime! Transform!", 
	         "Bleh,que massacre a CR fez aqui D:",
		 "Hayaaaa!!!!",
		 "Eu quero levar um Angkor pra casa <3",
	         "De olhos vermelhos, de pelo branquinho, DW pegou sua alma, e deixou num potinho.",
		 "Todo natal a Rena some -.-'",
		 "WS tem bom gosto, por isso escolheu o Ventus qq",
	         "Rena sambando na avenida ao som de marchinha de carnaval: ô ô ô Aurora!",
	         "Lince Negra. Noturna. X-men: Evolution!",
		 "Neste momento uma conferência de Lolis ocorre na sala Luciel",
		 "Quem joga com capricho. Joga com Primor!",
	         "Atitude perversa quem tira sarro da Quiliarca u_u",
	         "Lu me disse que não gosta de Gurren Lagann, mas sim **D'iVangelion**",
		 "Quando que o Raven vem me substituir? -.-'",
		 "Acho que o BM ficou muito Furioso D:",
	         "Redimido, compareça ao RH o quanto antes.",
	         "Para você velha, para o Imperador nova",
		 "Pi....Ka....Chunnnng!!!!",
		 "Este último look do Templário Cósmico ficou um ar-ra-so!",
	         "Convidei o Chung para assistir Os caça-fantasmas mas ele não gostou da ideia ;-;",
	         "Disseram pro Chung quando pediu pra esperarem ele pegar terceira classe: Sem tu irão",
		 "O DDD pra Add o Add...3ioo38282j83c398c239n. **Fatal Error: Error on NaN Class.** ",
		 "Há quanto tempo não vejo o Esper diabólico!Tá, essa foi péssima :C",
	         "Add cansou de ser engenheiro de dados e resolveu acompanhar o brasileirão!",
	         "O Psyker usa set de secret, já o Arauto do Caos",
		 "Reshian submersa está pegando fogo!",
		 "Vou roubar todos os Poporus da Lupina <3",
		 "Desculpa, tava lavando o cabelo qq",
		 "Me deixa dormirrrrrrrrrrr >w<",
		 "Parabéns! Descobriu a frase super secreta da Myu! Receberá um presente surpresa em 24 horas uwu",
	      	 "Lupina, devolve meu poporu!!!! ;-;",
	         "Esse canal é de Elsword? Me disseram que era da Elesis ;-;",
	         "Myu não pode atender no momento, deixe recado após o sinal: BEEEEEP!",
	         "Clanc! Clanc! Acho que meus neurônios estão enferrujados x_x",
	         "Go! Go! Myurangers!",
	         "Você disse, pipoca?",
	         "Procura-se: Poporu que a Lupina me roubou ;-;",
	         "Cinco guilitos foram passear. Além da Capela para brincar!",
	         "No meu casamento só vou de Véu se o Vel der.",
	         "Estou comendo bolachas, passe depois u_u",
	         "Meu custo em ED ficou mais caro ;-;",
	         "Estou trabalhando a 24 horas nesse canal e não ganhei nenhum poporu ;-;",
	         "Eu só peço a Deus!!! Um pouco de fadinhagem!!! <3"
		 ];
   }
}
